# Generated by Django 6.0.2 on 2026-02-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
