# Generated by Django 6.0.2 on 2026-02-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testresult_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='message',
            field=models.TextField(),
        ),
    ]
